const express = require('express');
const app = express();
const bodyParser = require('body-parser');
const router = express.Router();
const config = require('./config/config.json');
const port = process.env.PORT || config.port || 3000;
const Blog = require('./models/blog').Blog;
const logger = require('./logger/logger');
const blogs = require('./app/routes')(router, logger, Blog);
const errorHandler = require('./errorHandler/errorHandler')(logger);
const passport_oauth2 = require('passport-oauth2');
const passport_google = require('passport-google-oauth');

app.use(bodyParser.urlencoded({extended: true}));
app.use(bodyParser.json());
app.set('view engine', 'pug');
app.set('views', './views');
app.get('/', logger.initLogger);
app.use('/api', router);
app.use(errorHandler.e400);
app.use(errorHandler.e404);
app.use(errorHandler.e500);
app.listen(port);